services:
  main:
    container_name: gotodo
    build: .
    ports:
      - "8448:8447"
    restart: on-failure
    depends_on:
      my-postgres:
        condition: service_healthy
    networks:
      - ps

  my-postgres:
    hostname: my-postgres
    image: postgres
    container_name: my-postgres
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:         
      POSTGRES_HOST: my-postgres
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "postgres"
    volumes: 
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - ps
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - ps
networks:
  ps:
